#!/bin/bash
#######################################################################
## Towboat: Managing docker containers with simple configuration files
#######################################################################
## Author     : Bart Meuris <bart.meuris@gmail.com>
## Version    : 0.2 Alpha
##
#######################################################################
## Todo:
## - Add more commandline options
## - Add environment configuration and load /etc/default/towboat if it
##   exists.
## - Testing
## - More testing
#######################################################################
set -m

#LOGLEVEL=1 # ABORT/FATAL/OK
#LOGLEVEL=2 # ERROR
#LOGLEVEL=3 # WARN
#LOGLEVEL=4 # LOG

CONFIGPATH=${TOWBOAT_CONFIGPATH:-"/etc/towboat/"}
PIPEWORK=${PIPEWORK:-$(which pipework 2>/dev/null)}
PIPEWORK=${PIPEWORK:-"/usr/bin/pipework"}
DOCKER=${DOCKER:-$(which docker 2>/dev/null)}
DOCKER=${DOCKER:-"/usr/bin/docker"}
LOGLEVEL=${LOGLEVEL:-4}
DOCKERVERSION="$(docker -v | sed -e "s/.* version \(.*\),.*/\1/")"

DOCKER_NAMEOPT="--name"
DOCKER_LINKOPT="--link"

if [ "$(printf "0.9.0\n${DOCKERVERSION}\n" | sort | tail -n1)" != "$DOCKERVERSION" ]; then
	# Pre 0.9.0 the parameters used a single dash
	DOCKER_NAMEOPT="-name"
	DOCKER_LINKOPT="-link"
fi

function _log() {
	if [ -z "$1" ]; then
		TYPE="LOG"
	else
		TYPE=$1
		shift 1
	fi
	echo "[$(date +"%Y-%m-%d %H:%M:%S")] $TYPE: $*"
}

function log() {
	[ $LOGLEVEL -lt 4 ] && return
	_log "LOG" "$*"
}
function warn() {
	[ $LOGLEVEL -lt 3 ] && return
	_log "WARN" "$*"
}
function error() {
	[ $LOGLEVEL -lt 2 ] && return
	_log "ERROR" "$*"
}

function ok() {
	[ $LOGLEVEL -lt 1 ] && return
	_log "OK" "$*"
}

function fatal() {
	[ $LOGLEVEL -lt 1 ] && return
	_log "FATAL" "$*"
}
function abort() {
	[ $LOGLEVEL -lt 1 ] && return
	_log "ABORT" "$*"
	exit 1
}

function checkval
{
	VAL=$1
	[ -z "$VAL" ] && VAL="${2:-false}"
	case "$(echo $VAL|tr A-Z a-z)" in
	"false"|"f"|"n"|"0")
		echo "false"
		return 1
		;;
	"true"|"t"|"y"|"1")
		echo "true"
		return 0;
		;;
	*)
		echo $VAL
		;;
	esac
	return 0
}

###################################

function getconfigfiles()
{
	find $CONFIGPATH -maxdepth 1 -name "*.cfg" | sort
}

TOWBOAT_CONFIGS=(
	"ENABLED"
	"NAME"
	"IMAGE"
	"AUTO_REMOVE"
	"DATA_CONTAINER"
	"DOCKER_HOST"
	"DOCKER_PARAM"
	"CONTAINER_HOSTNAME"
	"CONTAINER_PARAM"
	"CONTAINER_ENV"
	"NETWORK_DISABLED"
	"PORTS_ALL"
	"PORTS"
	"VOLUMES"
	"VOLUMES_FROM"
	"LINKS"
	"PW_ENABLED"
	"PW_HOSTIF"
	"PW_CONTAINER_IF"
	"PW_IP"
	"PW_GATEWAY"
	"PW_MAC"
)

TOWBOAT_ENV=(
	"CONFIG_FILE"
	"RUN_ID"
	"MD5"
)

function printenv_arr()
{
	readarray -t SORT_ARR < <( for a in $*; do echo "$a"; done | sort )
	for v in "${SORT_ARR[@]}"; do
		if declare -p $v 2>/dev/null | grep -q 'declare \-a'; then
			# It's an array, loop
			while read av; do
				echo "ENV: $v[]: $av"
			done  < <(for b in $(eval echo '${'$v'[@]}'); do echo "$b"; done| sort)
		else
			# Normal variable, skip if empty
			local VAL="$(eval echo '$'$v)"
			[ -n "$VAL" ] && echo "ENV: $v: $VAL"
		fi
	done
}

function printenv()
{
	# Dump the Settings from config file
	echo "--- CONFIG START: $CONFIG_FILE ---"
	# Sort the keys, important for config change detection
	# while read v; do
		# if declare -p $v 2>/dev/null | grep -q 'declare \-a'; then
			## It's an array, loop
			# while read av; do
				# echo "ENV: $v[]: $av"
			# done  < <(for b in $(eval echo '${'$v'[@]}'); do echo "$b"; done| sort)
		# else
			## Normal variable, skip if empty
			# local VAL="$(eval echo '$'$v)"
			# [ -n "$VAL" ] && echo "ENV: $v: $VAL"
		# fi
	# done < <(for b in "${TOWBOAT_CONFIGS[@]}"; do echo "$b"; done| sort)
	printenv_arr "${TOWBOAT_CONFIGS[@]}"
	
	if [ -z "$1" ]; then
		echo "-- RUNTIME ENV --"
		printenv_arr "${TOWBOAT_ENV[@]}"
	fi
	echo "--- CONFIG END: $CONFIG_FILE---"
}

function resetenv()
{
	# Settings from config file
	for v in "${TOWBOAT_CONFIGS[@]}" "${TOWBOAT_ENV[@]}"; do
		eval $v=""
	done
}

function loadconfig()
{
	local CONFIG_FILE CNAME IFIPS
	# Reset the environment
	resetenv
	
	CNAME=$(echo "$1" | sed -e "s#.*/\(.*\)\.cfg#\1#")
	CONFIG_FILE=$1
	# Load the config file
	[ ! -f "$CONFIG_FILE" ] && {
		error "Could not start container $CNAME: $CONFIG_FILE doesn't exist"
		return 1
	}
	. $CONFIG_FILE
	# Check the container name
	if [ "$CNAME" != "$NAME" ]; then
		error "Container name and file name do not match: $CONFIG_FILE -> $NAME"
		resetenv
		return 1
	fi
	if [ -n "$PORTS" ]; then
		local P
		local TMP_PORTS
		local TMPA
		for P in "${PORTS[@]}"; do
			if [ "$(echo $P|grep "^@.*:")" ]; then
				# Extract the "@if" interface name in the portmapping
				local PIF=$(echo $P | sed -e "s#^@\([^:]*\):.*#\1#")
				# Get the IP Address from the interface. Only the first-one is picked up
				local PIP=$(ip addr show $PIF 2>/dev/null | grep "inet " | head -n1 | awk '{ print $2 }' | sed -e "s#^\(.*\)/.*#\1#")
				[ -z "$PIP" ] && {
					error "$NAME: Could not determine the IP Address for interface $PIF in port mapping $P - skipping"
					continue
				}
				TMPA=( "$(echo $P|sed -e "s/^@${PIF}:/${PIP}:/")" )
				IFIPS="${IFIPS} ${PIF}=${TMPA[0]}"
			else
				TMPA=( "$P" )
			fi
			TMP_PORTS=( "${TMP_PORTS[@]}" "${TMPA[@]}" )
		done
		PORTS=("${TMP_PORTS[@]}")
	fi
	
	# Create the DOCKER_HOST commandline parameter
	[ -n "$DOCKER_HOST" ] && DOCKER_HOST="-H=$DOCKER_HOST"
	
	## For compatability with old TOWBOAT_CONFIG format, use md5 on config file
	local ENV_MD5=$(findenv TOWBOAT_CONFIG)
	if [ -n "$ENV_MD5" ] && [ -z "$(echo $ENV_MD5|grep "^V2_")" ]; then
		warn "$NAME: Uses old TOWBOAT_CONFIG environment variable!"
		# We use the old config, use md5 directly on the configuration file
		if [ -n "$IFIPS" ]; then
			MD5=$( (cat ${CONFIG_FILE} ; echo "$IFIPS") | md5sum | awk '{ print $1 }')
		else
			MD5=$( cat ${CONFIG_FILE} | md5sum | awk '{ print $1 }')
		fi
	fi
	
	## MD5 not filled in by previous versions
	if [ -z "$MD5" ]; then
		# Better changes detection this way, use the evaluated output, fixes changing the config with scripts
		MD5="V2_$( printenv no_internal | md5sum | awk '{ print $1 }')"
	fi
	#printenv
	return 0
}


function run_pipework()
{
	local PW_OPT

	[ "$(checkval "$PW_ENABLED" false)" == "false" ] && return 0
	log "$NAME: Pipework enabled"

	[ ! -x "$PIPEWORK" ] && abort "Could not locate Pipework executable ($PIPEWORK)!"
	
	[ -z "$PW_HOSTIF" ] && {
		error "$NAME: Could not start pipework, host interface not defined"
		return 1
	}
	
	[ -n "$PW_CONTAINER_IF" ] && PW_OPT="$PW_OPT -i $PW_CONTAINER_IF"
	
	if [ -z "$PW_IP" ]; then
		PW_IP="dhcp"
	elif [ "$PW_IP" != "dhcp" ]; then
		if [ -z "$(echo $PW_IP)|grep "/[0-9]*$")" ]; then
			warn "No netmask specified, using $PW_IP/24"
			PW_IP="$PW_IP/24"
		fi
		[ -n "$PW_GATEWAY" ] && PW_IP="$PW_IP@$PW_GATEWAY"
	fi

	log "Running pipework: $PIPEWORK $PW_HOSTIF $PW_OPT $RUN_ID $PW_IP $PW_MAC"
	eval "$PIPEWORK $PW_HOSTIF $PW_OPT $RUN_ID $PW_IP $PW_MAC" || return 1
	return 0
}

function find_container() {
	local NOT_RUNNING CONT
	[ "$1" == "-a" ] && {
		NOT_RUNNING=1
		shift 1
	}
	CONT=${1:-$NAME}
	
	ID=$($DOCKER $DOCKER_HOST inspect -format "{{.ID}}" $CONT 2>/dev/null) || return 1
	if [ -z "$NOT_RUNNING" ] && [ "$($DOCKER $DOCKER_HOST inspect -format "{{.State.Running}}" $CONT 2>/dev/null)" != "true" ]; then
		return 1
	fi
	echo $ID
	return 0
}

## Find an environment variable stored in the container metadata
function findenv()
{
	local C D_ENV
	C=0
	while true; do
		D_ENV=$($DOCKER $DOCKER_HOST inspect -format="{{(index .Config.Env $C)}}" $NAME 2>/dev/null)
		C=$(( C + 1))
		[ -z "$D_ENV" ] && return 1
		[ -z "$(echo $D_ENV| grep "^$1=")" ] && continue
		echo $D_ENV|sed -e "s/^$1=\(.*\)$/\1/"
	done
	return 0
}

function check_dependency
{
	if [ -n "$(echo $DEPS_CHECKS|grep "|${1}|")" ]; then
		error "$ORIG_CONTAINER: Circular dependency detected when starting dependency $1"
		error "    Dependencies: ${DEPS_CHECKS}"
		return 1
	fi
	return 0
}

function add_dep_tree()
{
	DEPS_CHECKS="${DEPS_CHECKS}|$1|"
}
function rm_dep_tree()
{
	DEPS_CHECKS=$(echo $DEPS_CHECKS|sed -e "s/|$1|//")
}

## Run a dependency for the current container
function run_dependency()
{
	local ORIG_CONTAINER=$1
	local DEP=$2
	local CFGFILE=
	
	if ! check_dependency "$DEP"; then
		resetenv
		return 1
	fi
	add_dep_tree "$DEP"
	
	CFGFILE=$(getconfigfiles | grep "/${DEP}.cfg\$" | tail -n1)
	if [ -z "$CFGFILE" ]; then
		error "$ORIG_CONTAINER: Dependency '$DEP' does not have a config file"
		resetenv
		return 1
	fi
	startcontainer $CFGFILE || {
		error "$ORIG_CONTAINER: Dependency '$DEP' could not be started"
		resetenv
		return 1
	}
	rm_dep_tree "$DEP"
	return 0
}

## Check dependencies for the current container
function check_dependencies()
{
	local ORIG_CONTAINER DEP DEP_LINKS DEP_VOLUMES_FROM DEP_SET
	ORIG_CONTAINER=$NAME
	DEP_LINKS=$LINKS
	DEP_VOLUMES_FROM=$VOLUMES_FROM
	
	check_dependency "$ORIG_CONTAINER" > /dev/null 2>&1 && {
		## Inject the current container if it did not exist.
		add_dep_tree "$ORIG_CONTAINER"
		DEP_SET=1
	}

	# Check if the 'link' dependencies are running, and start if needed
	for DEP in $DEP_LINKS; do
		if [ -z "$(find_container $DEP)" ]; then
			log "$ORIG_CONTAINER: starting dependency $DEP"
			run_dependency "$ORIG_CONTAINER" "$(echo $DEP|sed -e "s/^\(.*\):.*/\1/")" || {
				resetenv
				return 1
			}
		fi
	done
	
	# Check if the data-volumes dependencies exist, and start if needed
	for DEP in $DEP_VOLUMES_FROM; do
		if [ -z "$(find_container -a $DEP)" ]; then
			log "$ORIG_CONTAINER: creating/starting dependency $DEP"
			run_dependency "$ORIG_CONTAINER" "$DEP" || {
				resetenv
				return 1
			}
		fi
	done
	
	# Remove the current container if it did not exist before.
	[ -n "$DEP_SET" ] && rm_dep_tree "$ORIG_CONTAINER"
	
	# Reload our own config
	loadconfig $(getconfigfiles | grep "/${ORIG_CONTAINER}.cfg\$" | tail -n1) || {
		resetenv
		return 1
	}
	return 0
}

#
function full_start()
{
	local _NAME=$NAME
	local _DOPTS=
	local ETHDEVS
	check_dependencies || {
		fatal "$_NAME NOT STARTED"
		resetenv
		return 1
	}
	_DOPTS="-d $DOCKER_NAMEOPT "$NAME" --hostname ${CONTAINER_HOSTNAME:-$NAME} -e TOWBOAT_CONFIG=$MD5"
	
	## Add networking environment
	if [ "$(checkval "$PW_ENABLED" false)" != "false" ]; then
		if [ "$(checkval "$NETWORK_DISABLED" false)" == "true" ]; then
			ETHDEVS="${PW_CONTAINER_IF:-eth1}"
		elif [ "${PW_CONTAINER_IF}" == "eth0" ]; then
			ETHDEVS="eth0"
		else
			ETHDEVS="eth0 ${PW_CONTAINER_IF:-eth1}"
		fi
	elif [ "$(checkval "$NETWORK_DISABLED" false)" == "true" ]; then
		ETHDEVS=""
	else
		ETHDEVS="eth0"
	fi
	_DOPTS="$_DOPTS -e ETHDEVS='$ETHDEVS'"
	
	## Add the environment
	if [ -n "$CONTAINER_ENV" ]; then
		local E
		for E in "${CONTAINER_ENV[@]}"; do
			_DOPTS="$_DOPTS -e $E"
		done
	fi
	## Add links with other containers
	if [ -n "$LINKS" ]; then
		local L
		for L in "${LINKS[@]}"; do
			_DOPTS="$_DOPTS $DOCKER_LINKOPT $L"
		done
	fi
	
	# Check the network
	[ "$(checkval "$NETWORK_DISABLED" false)" == "true" ] && _DOPTS="${_DOPTS} -n"
	# Process the ports
	[ "$(checkval "$PORTS_ALL" false)" == "true" ] && _DOPTS="${_DOPTS} -P"
	if [ -n "$PORTS" ]; then
		local P
		for P in "${PORTS[@]}"; do
			_DOPTS="$_DOPTS -p $P"
		done
	fi
	
	## Process the volumes
	if [ -n "$VOLUMES" ]; then
		for V in "${VOLUMES[@]}"; do
			_DOPTS="${_DOPTS} -v $V"
		done
	fi
	
	## Automatically mount local timezone and localtime files to the containers so they have the correct date/time 
	if [ "$(checkval "$AUTO_TIMEZONE" true)" == "true" ]; then
		if [ -f "/etc/localtime" ]; then
			_DOPTS="${_DOPTS} -v /etc/localtime:/etc/localtime:ro"
		fi
		if [ -f "/etc/timezone" ]; then
			_DOPTS="${_DOPTS} -v /etc/timezone:/etc/timezone:ro"
		fi
	fi
	if [ -n "$VOLUMES_FROM" ]; then
		for VF in "${VOLUMES_FROM[@]}"; do
			_DOPTS="${_DOPTS} --volumes-from $VF"
		done
	fi

	RUN_ID=$(eval "$DOCKER $DOCKER_HOST run $DOCKER_PARAM $_DOPTS $IMAGE $CONTAINER_PARAM") || {
		error "Docker run failed: $DOCKER $DOCKER_HOST run $DOCKER_PARAM $_DOPTS $IMAGE $CONTAINER_PARAM"
		fatal "$NAME NOT STARTED"
		resetenv
		return 1
	}
}

function restart()
{
	local MD5R
	local _NAME=$NAME

	## Assume container is not running
	MD5R=$(findenv TOWBOAT_CONFIG)

	if [ $(checkval $DATA_CONTAINER false) == "true" ]; then
		# Container does not have to run, just exist - which it does if we get here.
		if [ "$MD5R" != "$MD5" ]; then
			warn "$NAME is an existing data-container, and configuration has changed since start, NOT REMOVING."
		else
			log "$NAME is an existing data-container, no need to start."
		fi
		return 0
	fi

	if [ -z "$MD5R" ]; then
		# TOWBOAT_CONFIG env var not set - not started by towboat?
		warn "$NAME: Not started by Towboat (TOWBOAT_CONFIG env var not found) - restarting..."
		check_dependencies
		[ -z "$MD5" ] && {
			fatal "$_NAME NOT STARTED"
			return 1
		}
		
		RUN_ID=$($DOCKER $DOCKER_HOST start $NAME) || {
			error "$_NAME: docker start failed"
			fatal "$NAME NOT STARTED"
			return 1
		}
	elif [ "$MD5R" == "$MD5" ]; then
		# Same configuration file, just restart if needed
		check_dependencies || {
			error "$_NAME: Dependencies check failed"
			fatal "$_NAME NOT STARTED"
			return 1
		}
		RUN_ID=$($DOCKER $DOCKER_HOST start $NAME) || {
			error "$NAME: docker start failed"
			fatal "$NAME NOT STARTED"
			return 1
		}
	elif [ "$(checkval "$AUTO_REMOVE" false)" == "true" ]; then
		# Autoremove is on, this means first removing the container, then performing a full start
		#log "$NAME: Autoremove enabled, removing old instance before re-creating"
		$DOCKER $DOCKER_HOST rm $NAME >/dev/null || {
			error "$NAME: Autoremove enabled, config updated but remove failed!"
			fatal "$NAME NOT STARTED"
			return 1
		}
		full_start || return 1
	fi
	return 0
}

function containerstatus() {
	loadconfig $1 || return 1
	
	local CONFIG_UPDATED=
	MD5R=$(findenv TOWBOAT_CONFIG)
	if [ -n "$MD5R" ]; then
		if [ "$MD5" != "$MD5R" ]; then
			CONFIG_UPDATED=" - !! Configuration changed"
		else
			CONFIG_UPDATED=""
		fi
	else
		CONFIG_UPDATED="- No configuration env stored"
	fi

	if [ "$(checkval "$ENABLED" true)" == "false"  ]; then
		if [ -n "$(find_container)" ]; then
			warn "$NAME: Disabled, but running $CONFIG_UPDATED"
			[ -n "$CONFIG_UPDATED" ] && warn "-> $NAME: When restarting, the container will be killed."
		else
			ok "$NAME: Disabled $CONFIG_UPDATED"
		fi
		return 0
	elif [ -n "$(find_container)" ]; then
		ok "$NAME: Running $CONFIG_UPDATED"
		[ -n "$CONFIG_UPDATED" ] && warn "-> $NAME: start or restart container to apply new settings"
	elif [ -n "$(find_container -a)" ]; then
		if [ "$(checkval "$DATA_CONTAINER" false)" == "true" ]; then
			ok "$NAME: Data container exists $CONFIG_UPDATED"
			[ -n "$CONFIG_UPDATED" ] && warn "-> $NAME: towboat will not recreate container to avoid data loss!"
		else
			error "$NAME: Container exists but not running $CONFIG_UPDATED"
			[ -n "$CONFIG_UPDATED" ] && warn "-> $NAME: Start to apply the new settings"
			return 1
		fi
	else
		error "$NAME: Container does not exist!"
		return 1
	fi
	return 0
}

function stopcontainer() {
	loadconfig $1 || return 1
	if [ -z "$(find_container)" ]; then
		ok "$NAME: already stopped"
	elif [ -z "$(find_container -a)" ]; then
		warn "$NAME: container does not exist"
	else
		$DOCKER $DOCKER_HOST kill $NAME >/dev/null || {
			error "$NAME: error while stopping the container!"
			return 1
		}
		ok "$NAME: stopped."
	fi
	return 0
}

function startcontainer() {
	[ -n "$(echo $CONTAINERS_STARTED | grep "|$1|")" ] && return 0
	[ -n "$(echo $CONTAINERS_FAILED | grep "|$1|")" ] && {
		warn "'$1' already failed before, not attempting to start it again."
		return 1
	}
	
	#log "Starting container from file: $1"
	loadconfig $1 || return 1
	if [ "$(checkval "$ENABLED" true)" == "false"  ]; then
		if [ -n "$(find_container)" ]; then
			warn "$NAME: Disabled container running -> Stopping"
			$DOCKER $DOCKER_HOST kill $NAME >/dev/null || {
				fatal "$NAME: Could not kill disabled container"
				resetenv
				CONTAINERS_FAILED=="${CONTAINERS_FAILED}|$1|"
				return 1
			}
		else
			warn "$NAME: disabled"
		fi
		return 0
	fi
	
	if [ -n "$(find_container)" ]; then
		# Already running, check if config matches environment
		if [ "$MD5" != "$(findenv TOWBOAT_CONFIG)" ]; then
			log "MD5 MISMATCH: $MD5!= $(findenv TOWBOAT_CONFIG)"
			if [ "$(checkval "$AUTO_REMOVE" false)" == "true" ]; then
				log "$NAME: config change detected, AUTO_REMOVE enabled, killing old instance."
				$DOCKER $DOCKER_HOST kill $NAME >/dev/null || {
					fatal "$NAME: Could not restart upon config change"
					resetenv
					CONTAINERS_FAILED=="${CONTAINERS_FAILED}|$1|"
					return 1
				}
				restart || {
					resetenv
					CONTAINERS_FAILED=="${CONTAINERS_FAILED}|$1|"
					return 1
				}
				#log "$NAME: Restart OK"
			else
				warn "$NAME running, but config changed, AUTO_REMOVE disabled!"
				ok "$NAME running"
				return 0
			fi
		else
			ok "$NAME already running"
			return 0
		fi
	elif [ -n "$(find_container -a)" ]; then
		# Exists but not running
		restart || {
			CONTAINERS_FAILED=="${CONTAINERS_FAILED}|$1|"
			return 1
		}
	else
		# Doesn't exist, 
		full_start || {
			CONTAINERS_FAILED=="${CONTAINERS_FAILED}|$1|"
			return 1
		}
	fi
	run_pipework || {
		error "$NAME applying pipework settings failed - killing and removing container..."
		$DOCKER $DOCKER_HOST kill $NAME >/dev/null || {
			error "$NAME: Could not kill container after pipework failed"
			resetenv
			return 1
		}
		$DOCKER $DOCKER_HOST rm $NAME >/dev/null || {
			error "$NAME: Could not remove killed container after pipework failed"
			resetenv
			return 1
		}
		return 1
	}
	ok "$NAME started."
	CONTAINERS_STARTED="${CONTAINERS_STARTED}|$1|"
}

function towboat_run()
{
	# Commandline parameters passed, these should be specific containers to start
	RUNACTION=$1
	FNC=$2
	shift 2
	[ -z "$FNC" ] && return 2

	if [ -n "$1" ]; then
		FAIL=
		while [ -n "$1" ]; do
			CFGF=$(getconfigfiles | grep "/${1}.cfg\$" | tail -n1)
			[ -z "$CFGF" ] && {
				error "## Container '$1' config file not found in '$CONFIGPATH'!"
				FAIL="$FAIL $1"
				shift 1
				continue
			}
			$FNC $CFGF
			shift 1
		done
		[ -n "$FAIL" ] && {
			error "Failed $RUNACTION: $FAIL"
			return 1
		}
		return 0
	fi
	
	## Process all config files
	CONTAINERS_STARTED=
	CONTAINERS_FAILED=
	for F in $(getconfigfiles); do
		DEPS_CHECKS=
		$FNC $F
	done
	#echo CONTAINERS_STARTED: $CONTAINERS_STARTED
	#echo CONTAINERS_FAILED: $CONTAINERS_FAILED
	[ -n "$CONTAINERS_FAILED" ] && return 1
	return 0
}
function towboat_start()
{
	towboat_run "starting" "startcontainer" $*
	return $?
}

function towboat_status()
{
	towboat_run "checking the status of" "containerstatus" $*
	return $?
}
function towboat_stop()
{
	towboat_run "stopping" "stopcontainer" $*
	return $?
}

##################################################
## Startup

[ ! -x "$DOCKER" ] && abort "Could not locate Docker executable!"
CMD=$1
shift 1
case $CMD in
	start)
		towboat_start $* || exit 1
		;;
	stop)
		towboat_stop $* || exit 1
		;;
	restart)
		towboat_stop $* || exit 1
		towboat_start $* || exit 1
		;;
	status)
		towboat_status $* || exit 1
		;;
	*)
		echo "Usage: $0 start|stop|restart|status [containernames...]"
		exit 1
esac
exit 0
